### ISSUE TITLE
Uninstalling the eid-archive deb package does not remove sources.list.d entry

### ISSUE THREAD

**Issue by mgeens** [Fedict/eid-archive#2]
I've tried installing the eid software through the eid-archive deb package for Ubuntu 17.10 at https://eid.belgium.be/nl/linux-eid-software-installatie . Installing the package worked, but doing an apt update failed because http://files.eid.belgium.be/debian/dists/artful/InRelease gave a timeout.

After removing the eid-archive package with apt remove, apt update still failed, because /etc/apt/sources.list.d/eid.list was left in place. It had to be manually deleted, which can't have been the intention.

**Comment by yoe** [comment]
That's because you said "apt remove", not "apt remove --purge" :-)

Purging the package should remove the eid.list configuration file. If it does not, please do not hesitate to reopen this issue.
