### ISSUE TITLE
files.eid.belgium.be is down

### ISSUE THREAD

**Issue by mgeens** [Fedict/eid-archive#3]
Attempting to contact the site eventually results in a timeout. files2.eid.belgium.be still works. I tried to report this through https://eid.belgium.be/nl/contact, but that failed when submitting: 'The requested URL was rejected. Please consult with your administrator.'

**Comment by yoe** [comment]
Yes, we know, we're working on it. This should hopefully be resolved this week still.

(the timeout that is, the contact form I'm not sure what the problem is; I'll escalate that internally)

**Comment by yoe** [comment]
this is now fixed
