### ISSUE TITLE
Please add support for Devuan

### ISSUE THREAD

**Issue by xrogaan** [Fedict/eid-archive#4]
[Devuan](https://devuan.org) is a systemd less distribution based on debian, for people in a hurry.

It should behave exactly the same as debian, unless your project depends on systemd.

**Comment by yoe** [comment]
Devuan is not likely to be supported as a separate distribution. However, the packages for Debian should work equally well with Devuan -- there is nothing systemd-specific in our packages, and this is not likely to change.

**Comment by xrogaan** [comment]
Sorry, I wasn't meaning to imply the software couldn't work on derivative. Whenever a user install eid-archive, the [post install routine](https://github.com/Fedict/eid-archive/blob/a7c2bd63111a7cf20f37e1bf4623bf1ea1b2e738/debian/postinst#L15) will default to xenial, which seems to be a ubuntu flavor instead of debian's stable. This behavior will force the user to edit its apt/sources.list files to correct the name of the distribution.

A proper way to approach the issue would be to ask an input from the user, who is likely to be the system administrator, in order to gather to right information.
