### ISSUE TITLE
use https for archive downloads

### ISSUE THREAD

**Issue by plenaerts** [Fedict/eid-archive#7]
I see the repo URL's don't use HTTPS. Is there a reason not to? If not, then HTTPS should be the default.

Changing to https://files.eid.belgium.be/debian in /etc/apt/sources.list.d/eid.list seems to work perfectly well.

**Comment by yoe** [comment]
Historical reason: older versions of Debian and Ubuntu didn't include `apt-transport-https` in the default installation, making it problematic to do so.

This has been fixed a while ago now, however, so perhaps it's time to update this now.

**Comment by plenaerts** [comment]
Thanks, I noticed yesterday that you fixed this.

👍
