### ISSUE TITLE
Warn ubuntu impish users that the firefox snap can't use pkcs11

### ISSUE THREAD

**Issue by plenaerts** [Fedict/eid-archive#8]
I just spent a lot of time checking and checking again what could be wrong in my impish setup until I found this bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1734371

It would be very nice to inform users on the [eid-archive download page](https://eid.belgium.be/nl)
1) that this blocking issue is there at the moment for the default snap install of firefox in impish;
2) that as a result eid card support for firefox in ubuntu 21,10 impish indri is broken; and
3) tell them to fall back to the apt alternative using `sudo snap remove firefox && sudo apt-get install firefox` (or better alternative?)

**Comment by Frederikus** [comment]
Hello,

Apologies for the time you lost on this, and thank you for reporting

A FAQ was written for this issue at: https://eid.belgium.be/en/faq/why-it-not-possible-use-eid-software-snap-andor-flatpak#7636

We'll check internally regarding the message on eid.belgium.be

**Comment by plenaerts** [comment]
Thanks. I had not even seen that FAQ.

Is there maybe a way to detect that users are installing *eid-* packages while using snap or flatpack installations of browsers and then point more specificly to that FAQ?

I realise this seems very specific to this latest ubuntu release, but it may not be going away soon for ubuntu and other distro's may be going to the snap or flatpack deploys too.

About the FAQ itself: is it a better idea to point users to manual installations over distro prepared packages?

**Comment by Frederikus** [comment]
I don't know of a way our apt package could check if a snap or flatpack browser installation is present, but I believe these installations are by default in the latest Ubuntu release. 

We might be able to check if an apt browser installation is present, and only when not, show the warning and FAQ link. (For the latest ubuntu eidmw packages e.g.)

Wouter is the expert on these matters, but he's on holidays this week, we'll discuss this futher with him.

**Comment by Frederikus** [comment]
The link to the FAQ is added next to the mention of Ubuntu Impish. (https://eid.belgium.be/en/linux-eid-software-installation)

**Comment by yoe** [comment]
I think this fixes the problem, so closing the issue. Please feel free to reopen if you believe there are outstanding problems still.

**Comment by yoe** [comment]
whoops, wrong issue :)

**Comment by plenaerts** [comment]
I believe there are options in your packages post_install : if you notice firefox to be installed as a snap and not as an apt package; then show a warning.

Not sure if that works with the ubuntu package managers, but did you check?

I don't think I can reopen ;-)

**Comment by yoe** [comment]
While it is indeed possible to produce a warning from the postinst script (using the debconf interface), this is not ideal; due to how the package is installed by many people, it is not guaranteed that they will even see the warning.

Much better to have a message on the download page, like we're doing now.

**Comment by plenaerts** [comment]
OK, thanks for that consideration.

What the FAQ does not cover is:
- Users who had the eid-mw and are upgrading ubuntu.
- Also, the FAQ is quite technical and only mentions ubuntu at the bottom. The typical ubuntu user probably does not understand much of the answer in the FAQ, but should very much care about the last line.
- The answer doesn't provide the solution either: uninstall the snap and install via apt or direct download (not my personal recommendation, but who am I ;-))

**Comment by yoe** [comment]
It actually does. From the FAQ:

> In the meantime, to resolve the problem, you can install a browser outside of snap or Flatpak. Possible options for this are the official downloads of Google Chrome (https://www.google.com/chrome/?platform=linux), or the official download of Firefox (https://www.mozilla.org/en-US/firefox/linux/).

Installing firefox through apt works too, obviously, but since Ubuntu have announced that they're planning to remove that possibility in 21.04, I don't think that's a very good recommendation at this time; in contrast, the alternative options provided in the FAQ will continue to work.

**Comment by plenaerts** [comment]
My apologies. I guess it shows how people read FAQ's very diagonally. I was looking for very clear "do this to fix it" style instructions, which you don't/can't/won't give.

Thanks for your attempts to make this more clear to users ;-)

**Comment by yoe** [comment]
I'm very reluctant to have a simple "do this to unbreak things" FAQ entry. Those might come across as "your distribution is broken, here's how you fix it" (I actually support the idea of moving browsers to snap; from a security POV that's a very good idea), or worse, "we don't know what we're doing, please keep your system outdated so you can still use your eID" (we do, but the newfangled stuff doesn't currently support PKCS#11). Hence the explanation.

We've tried to keep it as simple as possible (trust me, I can go a *lot* deeper in the technicalities), but given the above explanation, that is somewhat complicated.

**Comment by plenaerts** [comment]
Sure, I get it :+1: 
My last comment was not intend sarcastically. It's hard to explain that there's pro's and cons to what causes the problem and potential solutions.
